### ISSUE TITLE
caching from dockerhub

### ISSUE THREAD

**Issue by mmg10** [aws-samples/bottlerocket-images-cache#5]
I was able to cache images from ECR public repo, but caching images from dockerhub didn't work. I wanted to cache torchserve image. This is the command used.

`./snapshot.sh -r us-west-2 docker.io/pytorch/torchserve-kfs:0.8.2-gpu`

Although it completed successfully, in the k8s logs, it took 8 minutes to download the image.
Do we need to modify the apiclient arguments to make it work with dockerhub images?

Thanks

**Comment by yubingjiaocn** [comment]
The script should work well when caching Dockerhub images. You may need to check `ImagePullPolicy` of your deployment manifest file. It should be set as `IfNotPresent` or `Never` to use the cached image.

**Comment by mmg10** [comment]
So here is the image prefetched from ECR. It takes 1s to "download" the image (since it is already present) 
![code](https://github.com/aws-samples/bottlerocket-images-cache/assets/65535131/fb9a840f-fc29-49a3-846e-fffbaff46254)

And here it is for the torchserve's image which is from dockerhub. It took ~9m.
![sdxl](https://github.com/aws-samples/bottlerocket-images-cache/assets/65535131/977bb66d-a1cb-42ce-b809-6e590c942456)

In both cases, the `ImagePullPolicy` field was missing. Does it have anything to do with the `-n k8s.io` argument in `CTR_CMD`?

**Comment by yubingjiaocn** [comment]
> Does it have anything to do with the `-n k8s.io` argument in `CTR_CMD`?

No. `kubelet` will only use images in `k8s.io` namespace no matter what repository the image from. 

Per Kubernetes doc, if you omit the `imagePullPolicy` field, and you specify the digest for the container image, the `imagePullPolicy` is automatically set to `IfNotPresent`. However, the value of `imagePullPolicy` of the container is always set when the object is first created, and is not updated if the image's tag or digest later changes.

Can you try to add `ImagePullPolicy` manually and try again? Thank you.

**Comment by mmg10** [comment]
First, apologies for messing things. In an attempt to pull from docker, I changed the namespace from `k8s.io` to something else, that broke things.

How did I find it out? by changing line 159 in `snapshot.sh` from `images pull` to `image ls` and seeing the output via the next line. The `docker.io/pytorch/torchserve-kfs:0.8.2-gpu` image was missing. Upon changing the namespace back to `k8s.io`, the image was indeed cached.

However, changing the `imagePullPolicy` to `Never` **did not work!**. Maybe this is because the image is being identified via the digest and not the tag, but I am not sure.  
![fail](https://github.com/aws-samples/bottlerocket-images-cache/assets/65535131/a0697e57-df7d-4572-80b8-f66e58a3f893)

But, changing the `imagePullPolicy` to `IfNotPresent`  worked like a charm and it 'downloaded' the image in 1s.
![pass](https://github.com/aws-samples/bottlerocket-images-cache/assets/65535131/432eabff-1cdf-4c1d-a595-ffc29204d52c)
